name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
      options: --user 1001 --security-opt no-new-privileges
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n Sub::Util IO::Socket::IP
          cpanm -n Cpanel::JSON::XS EV Role::Tiny
          cpanm -n Test::Pod Test::Pod::Coverage
      - name: Run Tests
        run: PERL5LIB="$HOME/perl5/lib/perl5" prove -l t t/mojo t/mojolicious
        env:
          TEST_POD: 1
          TEST_EV: 1
